executable            = read_eic_files_chunks.sh
arguments             = $(chunk)

output                = logs/job.$(ClusterId).$(ProcId).out
error                 = logs/job.$(ClusterId).$(ProcId).err
log                   = logs/job.$(ClusterId).log

+JobFlavour           = "microcentury"
request_memory        = 200
request_cpus          = 1
request_disk          = 1024

initialdir            = $ENV(PWD)

queue chunk from inputfiles/chunks/chunk.list